const adikaram = [
  {
    Index: 1,
    Tamil: 'கடவுள் வாழ்த்து',
    English: 'The Praise of God',
    Transliteration: 'Katavul Vaazhththu',
    kurralStart: 1,
    kurralEnd: 10,
  },
  {
    Index: 2,
    Tamil: 'வான்சிறப்பு',
    English: 'The Blessing of Rain',
    Transliteration: 'Vaansirappu',
    kurralStart: 11,
    kurralEnd: 20,
  },
  {
    Index: 3,
    Tamil: 'நீத்தார் பெருமை',
    English: 'The Greatness of Ascetics',
    Transliteration: 'Neeththaar Perumai',
    kurralStart: 21,
    kurralEnd: 30,
  },
  {
    Index: 4,
    Tamil: 'அறன் வலியுறுத்தல்',
    English: 'Assertion of the Strength of Virtue',
    Transliteration: 'Aran Valiyuruththal',
    kurralStart: 31,
    kurralEnd: 40,
  },
  {
    Index: 5,
    Tamil: 'இல்வாழ்க்கை',
    English: 'Domestic Life',
    Transliteration: 'Ilvaazhkkai',
    kurralStart: 41,
    kurralEnd: 50,
  },
  {
    Index: 6,
    Tamil: 'வாழ்க்கைத் துணைநலம்',
    English: 'The Worth of a Wife',
    Transliteration: 'Vaazhkkaith Thunainalam',
    kurralStart: 51,
    kurralEnd: 60,
  },
  {
    Index: 7,
    Tamil: 'மக்கட்பேறு',
    English: 'The Wealth of Children',
    Transliteration: 'Pudhalvaraip Perudhal',
    kurralStart: 61,
    kurralEnd: 70,
  },
  {
    Index: 8,
    Tamil: 'அன்புடைமை',
    English: 'The Possession of Love',
    Transliteration: 'Anputaimai',
    kurralStart: 71,
    kurralEnd: 80,
  },
  {
    Index: 9,
    Tamil: 'விருந்தோம்பல்',
    English: 'Hospitality',
    Transliteration: 'Virundhompal',
    kurralStart: 81,
    kurralEnd: 90,
  },
  {
    Index: 10,
    Tamil: 'இனியவை கூறல்',
    English: 'The Utterance of Pleasant Words',
    Transliteration: 'Iniyavaikooral',
    kurralStart: 91,
    kurralEnd: 100,
  },
  {
    Index: 11,
    Tamil: 'செய்ந்நன்றியறிதல்',
    English: 'Gratitude',
    Transliteration: 'Seynnandri Aridhal',
    kurralStart: 101,
    kurralEnd: 110,
  },
  {
    Index: 12,
    Tamil: 'நடுவு நிலைமை',
    English: 'Impartiality',
    Transliteration: 'Natuvu Nilaimai',
    kurralStart: 111,
    kurralEnd: 120,
  },
  {
    Index: 13,
    Tamil: 'அடக்கம் உடைமை',
    English: 'The Possession of Self-restraint',
    Transliteration: 'Atakkamutaimai',
    kurralStart: 121,
    kurralEnd: 130,
  },
  {
    Index: 14,
    Tamil: 'ஒழுக்கம் உடைமை',
    English: 'The Possession of Decorum',
    Transliteration: 'Ozhukkamutaimai',
    kurralStart: 131,
    kurralEnd: 140,
  },
  {
    Index: 15,
    Tamil: 'பிறனில் விழையாமை',
    English: "Not coveting another's Wife",
    Transliteration: 'Piranil Vizhaiyaamai',
    kurralStart: 141,
    kurralEnd: 150,
  },
  {
    Index: 16,
    Tamil: 'பொறையுடைமை',
    English: 'The Possession of Patience, Forbearance',
    Transliteration: 'Poraiyutaimai',
    kurralStart: 151,
    kurralEnd: 160,
  },
  {
    Index: 17,
    Tamil: 'அழுக்காறாமை',
    English: 'Not Envying',
    Transliteration: 'Azhukkaaraamai',
    kurralStart: 161,
    kurralEnd: 170,
  },
  {
    Index: 18,
    Tamil: 'வெஃகாமை',
    English: 'Not Coveting',
    Transliteration: 'Veqkaamai',
    kurralStart: 171,
    kurralEnd: 180,
  },
  {
    Index: 19,
    Tamil: 'புறங்கூறாமை',
    English: 'Not Backbiting',
    Transliteration: 'Purangooraamai',
    kurralStart: 181,
    kurralEnd: 190,
  },
  {
    Index: 20,
    Tamil: 'பயனில சொல்லாமை',
    English: 'Against Vain Speaking',
    Transliteration: 'Payanila Sollaamai',
    kurralStart: 191,
    kurralEnd: 200,
  },
  {
    Index: 21,
    Tamil: 'தீவினையச்சம்',
    English: 'Dread of Evil Deeds',
    Transliteration: 'Theevinaiyachcham',
    kurralStart: 201,
    kurralEnd: 210,
  },
  {
    Index: 22,
    Tamil: 'ஒப்புரவறிதல்',
    English: 'Duty to Society',
    Transliteration: 'Oppuravaridhal',
    kurralStart: 211,
    kurralEnd: 220,
  },
  {
    Index: 23,
    Tamil: 'ஈ.கை',
    English: 'Giving',
    Transliteration: 'Eekai',
    kurralStart: 221,
    kurralEnd: 230,
  },
  {
    Index: 24,
    Tamil: 'புகழ்',
    English: 'Renown',
    Transliteration: 'Pukazh',
    kurralStart: 231,
    kurralEnd: 240,
  },
  {
    Index: 25,
    Tamil: 'அருளுடைமை',
    English: 'Compassion',
    Transliteration: 'Arulutaimai',
    kurralStart: 241,
    kurralEnd: 250,
  },
  {
    Index: 26,
    Tamil: 'புலால் மறுத்தல்',
    English: 'Abstinence from Flesh',
    Transliteration: 'Pulaanmaruththal',
    kurralStart: 251,
    kurralEnd: 260,
  },
  {
    Index: 27,
    Tamil: 'தவம்',
    English: 'Penance',
    Transliteration: 'Thavam',
    kurralStart: 261,
    kurralEnd: 270,
  },
  {
    Index: 28,
    Tamil: 'கூடா ஒழுக்கம்',
    English: 'Imposture',
    Transliteration: 'Kootaavozhukkam',
    kurralStart: 271,
    kurralEnd: 280,
  },
  {
    Index: 29,
    Tamil: 'கள்ளாமை',
    English: 'The Absence of Fraud',
    Transliteration: 'Kallaamai',
    kurralStart: 281,
    kurralEnd: 290,
  },
  {
    Index: 30,
    Tamil: 'வாய்மை',
    English: 'Veracity',
    Transliteration: 'Vaaimai',
    kurralStart: 291,
    kurralEnd: 300,
  },
  {
    Index: 31,
    Tamil: 'வெகுளாமை',
    English: 'Restraining Anger',
    Transliteration: 'Vekulaamai',
    kurralStart: 301,
    kurralEnd: 310,
  },
  {
    Index: 32,
    Tamil: 'இன்னா செய்யாமை',
    English: 'Not doing Evil',
    Transliteration: 'Innaaseyyaamai',
    kurralStart: 311,
    kurralEnd: 320,
  },
  {
    Index: 33,
    Tamil: 'கொல்லாமை',
    English: 'Not killing',
    Transliteration: 'Kollaamai',
    kurralStart: 321,
    kurralEnd: 330,
  },
  {
    Index: 34,
    Tamil: 'நிலையாமை',
    English: 'Instability',
    Transliteration: 'Nilaiyaamai',
    kurralStart: 331,
    kurralEnd: 340,
  },
  {
    Index: 35,
    Tamil: 'துறவு',
    English: 'Renunciation',
    Transliteration: 'Thuravu',
    kurralStart: 341,
    kurralEnd: 350,
  },
  {
    Index: 36,
    Tamil: 'மெய்யுணர்தல்',
    English: 'Truth-Conciousness',
    Transliteration: 'Meyyunardhal',
    kurralStart: 351,
    kurralEnd: 360,
  },
  {
    Index: 37,
    Tamil: 'அவா அறுத்தல்',
    English: 'Curbing of Desire',
    Transliteration: 'Avaavaruththal',
    kurralStart: 361,
    kurralEnd: 370,
  },
  {
    Index: 38,
    Tamil: 'ஊழ்',
    English: 'Fate',
    Transliteration: 'Oozh',
    kurralStart: 371,
    kurralEnd: 380,
  },
  {
    Index: 39,
    Tamil: 'இறைமாட்சி',
    English: 'The Greatness of a King',
    Transliteration: 'Iraimaatchi',
    kurralStart: 381,
    kurralEnd: 390,
  },
  {
    Index: 40,
    Tamil: 'கல்வி',
    English: 'Learning',
    Transliteration: 'Kalvi',
    kurralStart: 391,
    kurralEnd: 400,
  },
  {
    Index: 41,
    Tamil: 'கல்லாமை',
    English: 'Ignorance',
    Transliteration: 'Kallaamai',
    kurralStart: 401,
    kurralEnd: 410,
  },
  {
    Index: 42,
    Tamil: 'கேள்வி',
    English: 'Hearing',
    Transliteration: 'Kelvi',
    kurralStart: 411,
    kurralEnd: 420,
  },
  {
    Index: 43,
    Tamil: 'அறிவுடைமை',
    English: 'The Possession of Knowledge',
    Transliteration: 'Arivutaimai',
    kurralStart: 421,
    kurralEnd: 430,
  },
  {
    Index: 44,
    Tamil: 'குற்றங்கடிதல்',
    English: 'The Correction of Faults',
    Transliteration: 'Kutrangatidhal',
    kurralStart: 431,
    kurralEnd: 440,
  },
  {
    Index: 45,
    Tamil: 'பெரியாரைத் துணைக்கோடல்',
    English: 'Seeking the Aid of Great Men',
    Transliteration: 'Periyaaraith Thunaikkotal',
    kurralStart: 441,
    kurralEnd: 450,
  },
  {
    Index: 46,
    Tamil: 'சிற்றினம் சேராமை',
    English: 'Avoiding mean Associations',
    Transliteration: 'Sitrinanjeraamai',
    kurralStart: 451,
    kurralEnd: 460,
  },
  {
    Index: 47,
    Tamil: 'தெரிந்து செயல்வகை',
    English: 'Acting after due Consideration',
    Transliteration: 'Therindhuseyalvakai',
    kurralStart: 461,
    kurralEnd: 470,
  },
  {
    Index: 48,
    Tamil: 'வலியறிதல்',
    English: 'The Knowledge of Power',
    Transliteration: 'Valiyaridhal',
    kurralStart: 471,
    kurralEnd: 480,
  },
  {
    Index: 49,
    Tamil: 'காலமறிதல்',
    English: 'Knowing the fitting Time',
    Transliteration: 'Kaalamaridhal',
    kurralStart: 481,
    kurralEnd: 490,
  },
  {
    Index: 50,
    Tamil: 'இடனறிதல்',
    English: 'Knowing the Place',
    Transliteration: 'Itanaridhal',
    kurralStart: 491,
    kurralEnd: 500,
  },
  {
    Index: 51,
    Tamil: 'தெரிந்து தெளிதல்',
    English: 'Selection and Confidence',
    Transliteration: 'Therindhudhelidhal',
    kurralStart: 501,
    kurralEnd: 510,
  },
  {
    Index: 52,
    Tamil: 'தெரிந்து வினையாடல்',
    English: 'Selection and Employment',
    Transliteration: 'Therindhuvinaiyaatal',
    kurralStart: 511,
    kurralEnd: 520,
  },
  {
    Index: 53,
    Tamil: 'சுற்றந் தழால்',
    English: 'Cherishing Kinsmen',
    Transliteration: 'Sutrandhazhaal',
    kurralStart: 521,
    kurralEnd: 530,
  },
  {
    Index: 54,
    Tamil: 'பொச்சாவாமை',
    English: 'Unforgetfulness',
    Transliteration: 'Pochchaavaamai',
    kurralStart: 531,
    kurralEnd: 540,
  },
  {
    Index: 55,
    Tamil: 'செங்கோன்மை',
    English: 'The Right Sceptre',
    Transliteration: 'Sengonmai',
    kurralStart: 541,
    kurralEnd: 550,
  },
  {
    Index: 56,
    Tamil: 'கொடுங்கோன்மை',
    English: 'The Cruel Sceptre',
    Transliteration: 'Kotungonmai',
    kurralStart: 551,
    kurralEnd: 560,
  },
  {
    Index: 57,
    Tamil: 'வெருவந்த செய்யாமை',
    English: 'Absence of Terrorism',
    Transliteration: 'Veruvandhaseyyaamai',
    kurralStart: 561,
    kurralEnd: 570,
  },
  {
    Index: 58,
    Tamil: 'கண்ணோட்டம்',
    English: 'Benignity',
    Transliteration: 'Kannottam',
    kurralStart: 571,
    kurralEnd: 580,
  },
  {
    Index: 59,
    Tamil: 'ஒற்றாடல்',
    English: 'Detectives',
    Transliteration: 'Otraatal',
    kurralStart: 581,
    kurralEnd: 590,
  },
  {
    Index: 60,
    Tamil: 'ஊக்கம் உடைமை',
    English: 'Energy',
    Transliteration: 'Ookkamutaimai',
    kurralStart: 591,
    kurralEnd: 600,
  },
  {
    Index: 61,
    Tamil: 'மடி இன்மை',
    English: 'Unsluggishness',
    Transliteration: 'Matiyinmai',
    kurralStart: 601,
    kurralEnd: 610,
  },
  {
    Index: 62,
    Tamil: 'ஆள்வினை உடைமை',
    English: 'Manly Effort',
    Transliteration: 'Aalvinaiyutaimai',
    kurralStart: 611,
    kurralEnd: 620,
  },
  {
    Index: 63,
    Tamil: 'இடுக்கண் அழியாமை',
    English: 'Hopefulness in Trouble',
    Transliteration: 'Itukkan Azhiyaamai',
    kurralStart: 621,
    kurralEnd: 630,
  },
  {
    Index: 64,
    Tamil: 'அமைச்சு',
    English: 'The Office of Minister of state',
    Transliteration: 'Amaichchu',
    kurralStart: 631,
    kurralEnd: 640,
  },
  {
    Index: 65,
    Tamil: 'சொல்வன்மை',
    English: 'Power of Speech',
    Transliteration: 'Solvanmai',
    kurralStart: 641,
    kurralEnd: 650,
  },
  {
    Index: 66,
    Tamil: 'வினைத் தூய்மை',
    English: 'Purity in Action',
    Transliteration: 'Vinaiththooimai',
    kurralStart: 651,
    kurralEnd: 660,
  },
  {
    Index: 67,
    Tamil: 'வினைத்திட்பம்',
    English: 'Power in Action',
    Transliteration: 'Vinaiththitpam',
    kurralStart: 661,
    kurralEnd: 670,
  },
  {
    Index: 68,
    Tamil: 'வினை செயல்வகை',
    English: 'Modes of Action',
    Transliteration: 'Vinaiseyalvakai',
    kurralStart: 671,
    kurralEnd: 680,
  },
  {
    Index: 69,
    Tamil: 'தூது',
    English: 'The Envoy',
    Transliteration: 'Thoodhu',
    kurralStart: 681,
    kurralEnd: 690,
  },
  {
    Index: 70,
    Tamil: 'மன்னரைச் சேர்ந்து ஒழுகல்',
    English: 'Conduct in the Presence of the King',
    Transliteration: 'Mannaraich Cherndhozhudhal',
    kurralStart: 691,
    kurralEnd: 700,
  },
  {
    Index: 71,
    Tamil: 'குறிப்பறிதல்',
    English: 'The Knowledge of Indications',
    Transliteration: 'Kuripparidhal',
    kurralStart: 701,
    kurralEnd: 710,
  },
  {
    Index: 72,
    Tamil: 'அவை அறிதல்',
    English: 'The Knowledge of the Council Chamber',
    Transliteration: 'Avaiyaridhal',
    kurralStart: 711,
    kurralEnd: 720,
  },
  {
    Index: 73,
    Tamil: 'அவை அஞ்சாமை',
    English: 'Not to dread the Council',
    Transliteration: 'Avaiyanjaamai',
    kurralStart: 721,
    kurralEnd: 730,
  },
  {
    Index: 74,
    Tamil: 'நாடு',
    English: 'The Land',
    Transliteration: 'Naatu',
    kurralStart: 731,
    kurralEnd: 740,
  },
  {
    Index: 75,
    Tamil: 'அரண்',
    English: 'The Fortification',
    Transliteration: 'Aran',
    kurralStart: 741,
    kurralEnd: 750,
  },
  {
    Index: 76,
    Tamil: 'பொருள் செயல்வகை',
    English: 'Way of Accumulating Wealth',
    Transliteration: 'Porulseyalvakai',
    kurralStart: 751,
    kurralEnd: 760,
  },
  {
    Index: 77,
    Tamil: 'படை மாட்சி',
    English: 'The Excellence of an Army',
    Transliteration: 'Pataimaatchi',
    kurralStart: 761,
    kurralEnd: 770,
  },
  {
    Index: 78,
    Tamil: 'படைச் செருக்கு',
    English: 'Military Spirit',
    Transliteration: 'Pataichcherukku',
    kurralStart: 771,
    kurralEnd: 780,
  },
  {
    Index: 79,
    Tamil: 'நட்பு',
    English: 'Friendship',
    Transliteration: 'Natpu',
    kurralStart: 781,
    kurralEnd: 790,
  },
  {
    Index: 80,
    Tamil: 'நட்பாராய்தல்',
    English: 'Investigation in forming Friendships',
    Transliteration: 'Natpaaraaidhal',
    kurralStart: 791,
    kurralEnd: 800,
  },
  {
    Index: 81,
    Tamil: 'பழைமை',
    English: 'Familiarity',
    Transliteration: 'Pazhaimai',
    kurralStart: 801,
    kurralEnd: 810,
  },
  {
    Index: 82,
    Tamil: 'தீ நட்பு',
    English: 'Evil Friendship',
    Transliteration: 'Thee Natpu',
    kurralStart: 811,
    kurralEnd: 820,
  },
  {
    Index: 83,
    Tamil: 'கூடா நட்பு',
    English: 'Unreal Friendship',
    Transliteration: 'Kootaanatpu',
    kurralStart: 821,
    kurralEnd: 830,
  },
  {
    Index: 84,
    Tamil: 'பேதைமை',
    English: 'Folly',
    Transliteration: 'Pedhaimai',
    kurralStart: 831,
    kurralEnd: 840,
  },
  {
    Index: 85,
    Tamil: 'புல்லறிவாண்மை',
    English: 'Ignorance',
    Transliteration: 'Pullarivaanmai',
    kurralStart: 841,
    kurralEnd: 850,
  },
  {
    Index: 86,
    Tamil: 'இகல்',
    English: 'Hostility',
    Transliteration: 'Ikal',
    kurralStart: 851,
    kurralEnd: 860,
  },
  {
    Index: 87,
    Tamil: 'பகை மாட்சி',
    English: 'The Might of Hatred',
    Transliteration: 'Pakaimaatchi',
    kurralStart: 861,
    kurralEnd: 870,
  },
  {
    Index: 88,
    Tamil: 'பகைத்திறம் தெரிதல்',
    English: 'Knowing the Quality of Hate',
    Transliteration: 'Pakaiththirandheridhal',
    kurralStart: 871,
    kurralEnd: 880,
  },
  {
    Index: 89,
    Tamil: 'உட்பகை',
    English: 'Enmity within',
    Transliteration: 'Utpakai',
    kurralStart: 881,
    kurralEnd: 890,
  },
  {
    Index: 90,
    Tamil: 'பெரியாரைப் பிழையாமை',
    English: 'Not Offending the Great',
    Transliteration: 'Periyaaraip Pizhaiyaamai',
    kurralStart: 891,
    kurralEnd: 900,
  },
  {
    Index: 91,
    Tamil: 'பெண்வழிச் சேறல்',
    English: 'Being led by Women',
    Transliteration: 'Penvazhichcheral',
    kurralStart: 901,
    kurralEnd: 910,
  },
  {
    Index: 92,
    Tamil: 'வரைவின் மகளிர்',
    English: 'Wanton Women',
    Transliteration: 'Varaivinmakalir',
    kurralStart: 911,
    kurralEnd: 920,
  },
  {
    Index: 93,
    Tamil: 'கள்ளுண்ணாமை',
    English: 'Not Drinking Palm-Wine',
    Transliteration: 'Kallunnaamai',
    kurralStart: 921,
    kurralEnd: 930,
  },
  {
    Index: 94,
    Tamil: 'சூது',
    English: 'Gambling',
    Transliteration: 'Soodhu',
    kurralStart: 931,
    kurralEnd: 940,
  },
  {
    Index: 95,
    Tamil: 'மருந்து',
    English: 'Medicine',
    Transliteration: 'Marundhu',
    kurralStart: 941,
    kurralEnd: 950,
  },
  {
    Index: 96,
    Tamil: 'குடிமை',
    English: 'Nobility',
    Transliteration: 'Kutimai',
    kurralStart: 951,
    kurralEnd: 960,
  },
  {
    Index: 97,
    Tamil: 'மானம்',
    English: 'Honour',
    Transliteration: 'Maanam',
    kurralStart: 961,
    kurralEnd: 970,
  },
  {
    Index: 98,
    Tamil: 'பெருமை',
    English: 'Greatness',
    Transliteration: 'Perumai',
    kurralStart: 971,
    kurralEnd: 980,
  },
  {
    Index: 99,
    Tamil: 'சான்றாண்மை',
    English: 'Perfectness',
    Transliteration: 'Saandraanmai',
    kurralStart: 981,
    kurralEnd: 990,
  },
  {
    Index: 100,
    Tamil: 'பண்புடைமை',
    English: 'Courtesy',
    Transliteration: 'Panputaimai',
    kurralStart: 991,
    kurralEnd: 1000,
  },
  {
    Index: 101,
    Tamil: 'நன்றியில் செல்வம்',
    English: 'Wealth without Benefaction',
    Transliteration: 'Nandriyilselvam',
    kurralStart: 1001,
    kurralEnd: 1010,
  },
  {
    Index: 102,
    Tamil: 'நாணுடைமை',
    English: 'Shame',
    Transliteration: 'Naanutaimai',
    kurralStart: 1011,
    kurralEnd: 1020,
  },
  {
    Index: 103,
    Tamil: 'குடிசெயல் வகை',
    English: 'The Way of Maintaining the Family',
    Transliteration: 'Kutiseyalvakai',
    kurralStart: 1021,
    kurralEnd: 1030,
  },
  {
    Index: 104,
    Tamil: 'உழவு',
    English: 'Farming',
    Transliteration: 'Uzhavu',
    kurralStart: 1031,
    kurralEnd: 1040,
  },
  {
    Index: 105,
    Tamil: 'நல்குரவு',
    English: 'Poverty',
    Transliteration: 'Nalkuravu',
    kurralStart: 1041,
    kurralEnd: 1050,
  },
  {
    Index: 106,
    Tamil: 'இரவு',
    English: 'Mendicancy',
    Transliteration: 'Iravu',
    kurralStart: 1051,
    kurralEnd: 1060,
  },
  {
    Index: 107,
    Tamil: 'இரவச்சம்',
    English: 'The Dread of Mendicancy',
    Transliteration: 'Iravachcham',
    kurralStart: 1061,
    kurralEnd: 1070,
  },
  {
    Index: 108,
    Tamil: 'கயமை',
    English: 'Baseness',
    Transliteration: 'Kayamai',
    kurralStart: 1071,
    kurralEnd: 1080,
  },
  {
    Index: 109,
    Tamil: 'தகை அணங்குறுத்தல்',
    English: 'The Pre-marital love',
    Transliteration: 'Thakaiyananguruththal',
    kurralStart: 1081,
    kurralEnd: 1090,
  },
  {
    Index: 110,
    Tamil: 'குறிப்பறிதல்',
    English: 'Recognition of the Signs',
    Transliteration: 'Kuripparidhal',
    kurralStart: 1091,
    kurralEnd: 1100,
  },
  {
    Index: 111,
    Tamil: 'புணர்ச்சி மகிழ்தல்',
    English: 'Rejoicing in the Embrace',
    Transliteration: 'Punarchchimakizhdhal',
    kurralStart: 1101,
    kurralEnd: 1110,
  },
  {
    Index: 112,
    Tamil: 'நலம் புனைந்து உரைத்தல்',
    English: 'The Praise of her Beauty',
    Transliteration: 'Nalampunaindhuraiththal',
    kurralStart: 1111,
    kurralEnd: 1120,
  },
  {
    Index: 113,
    Tamil: 'காதற் சிறப்புரைத்தல்',
    English: "Declaration of Love's special Excellence",
    Transliteration: 'Kaadharsirappuraiththal',
    kurralStart: 1121,
    kurralEnd: 1130,
  },
  {
    Index: 114,
    Tamil: 'நாணுத் துறவுரைத்தல்',
    English: 'The Abandonment of Reserve',
    Transliteration: 'Naanuththuravuraiththal',
    kurralStart: 1131,
    kurralEnd: 1140,
  },
  {
    Index: 115,
    Tamil: 'அலர் அறிவுறுத்தல்',
    English: 'The Announcement of the Rumour',
    Transliteration: 'Alararivuruththal',
    kurralStart: 1141,
    kurralEnd: 1150,
  },
  {
    Index: 116,
    Tamil: 'பிரிவு ஆற்றாமை',
    English: 'Separation unendurable',
    Transliteration: 'Pirivaatraamai',
    kurralStart: 1151,
    kurralEnd: 1160,
  },
  {
    Index: 117,
    Tamil: 'படர்மெலிந் திரங்கல்',
    English: 'Complainings',
    Transliteration: 'Patarmelindhirangal',
    kurralStart: 1161,
    kurralEnd: 1170,
  },
  {
    Index: 118,
    Tamil: 'கண் விதுப்பழிதல்',
    English: 'Eyes consumed with Grief',
    Transliteration: 'Kanvidhuppazhidhal',
    kurralStart: 1171,
    kurralEnd: 1180,
  },
  {
    Index: 119,
    Tamil: 'பசப்புறு பருவரல்',
    English: 'The Pallid Hue',
    Transliteration: 'Pasapparuparuvaral',
    kurralStart: 1181,
    kurralEnd: 1190,
  },
  {
    Index: 120,
    Tamil: 'தனிப்படர் மிகுதி',
    English: 'The Solitary Anguish',
    Transliteration: 'Thanippatarmikudhi',
    kurralStart: 1191,
    kurralEnd: 1200,
  },
  {
    Index: 121,
    Tamil: 'நினைந்தவர் புலம்பல்',
    English: 'Sad Memories',
    Transliteration: 'Ninaindhavarpulampal',
    kurralStart: 1201,
    kurralEnd: 1210,
  },
  {
    Index: 122,
    Tamil: 'கனவுநிலை உரைத்தல்',
    English: 'The Visions of the Night',
    Transliteration: 'Kanavunilaiyuraiththal',
    kurralStart: 1211,
    kurralEnd: 1220,
  },
  {
    Index: 123,
    Tamil: 'பொழுதுகண்டு இரங்கல்',
    English: 'Lamentations at Eventide',
    Transliteration: 'Pozhudhukantirangal',
    kurralStart: 1221,
    kurralEnd: 1230,
  },
  {
    Index: 124,
    Tamil: 'உறுப்புநலன் அழிதல்',
    English: 'Wasting Away',
    Transliteration: 'Uruppunalanazhidhal',
    kurralStart: 1231,
    kurralEnd: 1240,
  },
  {
    Index: 125,
    Tamil: 'நெஞ்சொடு கிளத்தல்',
    English: 'Soliloquy',
    Transliteration: 'Nenjotukilaththal',
    kurralStart: 1241,
    kurralEnd: 1250,
  },
  {
    Index: 126,
    Tamil: 'நிறையழிதல்',
    English: 'Reserve Overcome',
    Transliteration: 'Niraiyazhidhal',
    kurralStart: 1251,
    kurralEnd: 1260,
  },
  {
    Index: 127,
    Tamil: 'அவர்வயின் விதும்பல்',
    English: 'Mutual Desire',
    Transliteration: 'Avarvayinvidhumpal',
    kurralStart: 1261,
    kurralEnd: 1270,
  },
  {
    Index: 128,
    Tamil: 'குறிப்பறிவுறுத்தல்',
    English: 'The Reading of the Signs',
    Transliteration: 'Kuripparivuruththal',
    kurralStart: 1271,
    kurralEnd: 1280,
  },
  {
    Index: 129,
    Tamil: 'புணர்ச்சி விதும்பல்',
    English: 'Desire for Reunion',
    Transliteration: 'Punarchchividhumpal',
    kurralStart: 1281,
    kurralEnd: 1290,
  },
  {
    Index: 130,
    Tamil: 'நெஞ்சொடு புலத்தல்',
    English: 'Expostulation with Oneself',
    Transliteration: 'Nenjotupulaththal',
    kurralStart: 1291,
    kurralEnd: 1300,
  },
  {
    Index: 131,
    Tamil: 'புலவி',
    English: 'Pouting',
    Transliteration: 'Pulavi',
    kurralStart: 1301,
    kurralEnd: 1310,
  },
  {
    Index: 132,
    Tamil: 'புலவி நுணுக்கம்',
    English: 'Feigned Anger',
    Transliteration: 'Pulavi Nunukkam',
    kurralStart: 1311,
    kurralEnd: 1320,
  },
  {
    Index: 133,
    Tamil: 'ஊடலுவகை',
    English: 'The Pleasures of Temporary Variance',
    Transliteration: 'Ootaluvakai',
    kurralStart: 1321,
    kurralEnd: 1330,
  },
];

export default adikaram;
